/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rino.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Material.001']}
        geometry={nodes.Rino.geometry}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.06, 0.06, 0.06]}
      />
      <mesh
        material={materials['Material.002']}
        geometry={nodes.Horn.geometry}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.06, 0.06, 0.06]}
      />
    </group>
  )
}

useGLTF.preload('/rino.glb')
